server:
  port: 3001

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          # The public-facing address of the token issuer (Keycloak), as seen by the client.
          # This must match the 'iss' claim in the JWT.
          issuer-uri: http://localhost:8180/realms/veer
          # The internal network address for the Gateway to fetch public keys (JWKs)
          # from Keycloak to verify the JWT signature.
          jwk-set-uri: http://keycloak:8080/realms/veer/protocol/openid-connect/certs

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      enabled: true
      show-details: always

services:
  user:
    uri: http://veer-route:3002
  route:
    uri: http://veer-route:3003
