services:
  postgres:
    image: postgres:15
    container_name: veer-postgres
    restart: always
    environment:
      POSTGRES_DB: veer_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
    ports:
      - "25432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./services/postgres/init:/docker-entrypoint-initdb.d
    networks:
      - veer
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "admin", "-d", "veer_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.1
    container_name: veer-keycloak
    command:
      - start-dev
      - --features=preview
      - --hostname-strict=false
      - --proxy-headers=xforwarded
      - --spi-theme-cache-themes=false
      - --spi-theme-cache-templates=false
      - --spi-theme-static-max-age=-1
      - --import-realm
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: secret
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak_db
      KC_DB_USERNAME: admin
      KC_DB_PASSWORD: secret

    volumes:
      - ./services/keycloak/export:/opt/keycloak/import
      - ./services/keycloak/themes:/opt/keycloak/themes
    ports:
      - "8180:8080"
    depends_on:
      - postgres
    networks:
      - veer
  gateway:
    build: ./services/gateway
    container_name: veer-gateway
    restart: always
    ports:
      - "3101:3001"
    env_file:
      - ./services/gateway/.env
    depends_on:
      - keycloak
    networks:
      - veer

  user-service:
    build: ./services/veer-user
    container_name: veer-user-service
    restart: always
    # no ports exposed for the internal user service
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: veer_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
    depends_on:
      - postgres
    networks:
      - veer
  veer-route:
    build: ./services/veer-route
    container_name: veer-route
    # no ports exposed for the internal user service
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: veer_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - postgres
    networks:
      - veer

  nginx:
    image: nginx:alpine
    container_name: veer-nginx
    restart: unless-stopped
    ports:
      - "8088:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - gateway
      - keycloak
    networks:
      - veer

networks:
  veer:
    driver: bridge

volumes:
  postgres-data:
  # mongo-data:
# mongo:
#   image: mongo:6
#   container_name: veer-mongo
#   restart: unless-stopped
#   ports:
#     - "27028:27017"
#   volumes:
#     - mongo-data:/data/db
#   networks:
#     - veer
#   healthcheck:
#     test: echo 'db.runCommand("ping").ok' | mongo localhost:27017/test --quiet
#     interval: 10s
#     timeout: 5s
#     retries: 5

# redis:
#   image: redis:7
#   container_name: veer-redis
#   restart: unless-stopped
#   ports:
#     - "6389:6379"
#   networks:
#     - veer
#   healthcheck:
#     test: ["CMD", "redis-cli", "ping"]
#     interval: 5s
#     timeout: 3s
#
