spring:
  application:
    name: veer-route-service

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

  # JPA (Hibernate) configuration
  jpa:
    # Tells Hibernate to use the PostgreSQL dialect
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    
    # Data Definition Language settings
    hibernate:
      # 'update': Automatically updates the schema (adds columns, tables),
      # but does not delete data.
      ddl-auto: update
      
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 3003

management:
  endpoints:
    web:
      exposure:
        include: health,info

